# Generated by Django 3.2.9 on 2022-01-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='country',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='released_date',
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(default='Computer Science', max_length=250)),
                ('platform', models.CharField(default='YouTube', max_length=1000)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='India', max_length=1000)),
                ('language', models.CharField(default='English', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=4)),
                ('certificate', models.BooleanField(default=False)),
                ('material_type', models.CharField(choices=[('Videos', 'Videos'), ('Textual', 'Textual'), ('Hybrid', 'Hybrid')], default='Videos', max_length=25)),
                ('added_by', models.CharField(default='Neesham', max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinx.course')),
            ],
            options={
                'verbose_name_plural': 'Courses-details',
            },
        ),
    ]
