# Generated by Django 3.2.9 on 2021-12-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
