# Generated by Django 3.2.9 on 2021-12-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinx', '0002_rating_total_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='total_rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TotalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinx.course')),
            ],
        ),
    ]
