# Generated by Django 3.2.9 on 2021-12-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinx', '0003_auto_20211225_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
