# Generated by Django 3.2.9 on 2021-12-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinx', '0004_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['overall_rating'], 'verbose_name_plural': 'Courses-sinx'},
        ),
    ]
