# Generated by Django 3.2.8 on 2021-11-06 10:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20211106_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubinfo',
            options={'verbose_name_plural': 'Club-Info'},
        ),
        migrations.AlterModelOptions(
            name='clubverification',
            options={'verbose_name_plural': 'Verified Clubs'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventcomments',
            options={'verbose_name_plural': 'Event-Comments'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name_plural': 'Event-Registrations'},
        ),
        migrations.AlterModelOptions(
            name='eventupdates',
            options={'verbose_name_plural': 'Event-Updates'},
        ),
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Club-Discussions'},
        ),
        migrations.AlterModelOptions(
            name='taskchat',
            options={'verbose_name_plural': 'Club-Discussions-Updates'},
        ),
        migrations.AlterModelOptions(
            name='waitingarea',
            options={'verbose_name_plural': 'Waiting-Area'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 6, 15, 47, 29, 423570), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 6, 10, 17, 29, 445704, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 6, 10, 17, 29, 445704, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitors',
            },
        ),
    ]
