# Generated by Django 3.2.9 on 2022-01-15 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 15, 16, 52, 7, 905338), null=True),
        ),
    ]
