# Generated by Django 3.2.9 on 2022-01-14 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_event_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubinfo',
            name='private',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 14, 18, 17, 41, 313889), null=True),
        ),
    ]
