# Generated by Django 3.2.8 on 2021-10-31 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211031_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 31, 19, 18, 29, 770116), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 31, 13, 48, 29, 770116, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 31, 13, 48, 29, 770116, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='taskchat',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.task'),
        ),
    ]
