# Generated by Django 3.2.8 on 2021-10-31 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211031_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchat',
            name='task',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 31, 19, 21, 20, 654736), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 31, 13, 51, 20, 654736, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 31, 13, 51, 20, 654736, tzinfo=utc), null=True),
        ),
    ]
