# Generated by Django 3.2.9 on 2022-01-11 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220110_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 11, 14, 2, 58, 534415), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 11, 8, 32, 58, 550036, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 11, 8, 32, 58, 550036, tzinfo=utc), null=True),
        ),
    ]
