# Generated by Django 3.2.8 on 2021-11-15 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211112_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubverification',
            name='clg',
            field=models.CharField(default='Not Required', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 15, 19, 52, 3, 725705), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 15, 14, 22, 3, 741339, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 15, 14, 22, 3, 741339, tzinfo=utc), null=True),
        ),
    ]
