# Generated by Django 3.2.8 on 2021-11-01 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211031_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='tag',
            field=models.CharField(choices=[('DRAMA', 'DRAMA'), ('TECHNICAL', 'TECHNICAL'), ('SPRITUAL', 'SPRITUAL'), ('SPORTS', 'SPORTS'), ('MUSIC', 'MUSIC'), ('SOFTWARE', 'SOFTWARE'), ('ALL', 'ALL')], default='ALL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 1, 14, 20, 13, 236959), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 1, 8, 50, 13, 252579, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 1, 8, 50, 13, 252579, tzinfo=utc), null=True),
        ),
    ]
