# Generated by Django 3.2.9 on 2022-01-12 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220112_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 12, 21, 56, 26, 370788), null=True),
        ),
    ]
