# Generated by Django 3.2.9 on 2021-12-26 05:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211225_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 12, 26, 11, 29, 7, 667120), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 26, 5, 59, 7, 667120, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 12, 26, 5, 59, 7, 667120, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='StoryAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.story')),
            ],
        ),
    ]
