# Generated by Django 3.2.8 on 2021-11-25 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211121_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='tag',
            field=models.CharField(default='ALL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 25, 13, 56, 43, 219421), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 25, 8, 26, 43, 230499, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 11, 25, 8, 26, 43, 230499, tzinfo=utc), null=True),
        ),
    ]
