# Generated by Django 3.2.9 on 2021-12-26 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211226_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 12, 26, 16, 14, 5, 757690), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 26, 10, 44, 5, 773236, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 12, 26, 10, 44, 5, 773236, tzinfo=utc), null=True),
        ),
    ]
