# Generated by Django 3.2.9 on 2022-01-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_diary', '0003_sharecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecourse',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
